services:
  train:
    build:
      context: .
      dockerfile: docker/Dockerfile.train
    container_name: train
    tty: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./results/:/code/results/
      - ./models/:/code/models/
      - ./datasets/:/code/datasets/
    command: 'python train.py --dataset mnist --model stcoordconv --epochs 30'
    runtime: nvidia

  jupyter:
    build:
      context: .
      dockerfile: docker/Dockerfile.jupyter
    container_name: jupyter
    user: root
    ports:
      - 8888:8888
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=docker
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./jupyter/:/home/jovyan/work/jupyter/
    runtime: nvidia

